Repository antvis/LarkMap, pull requests merged in 2022-10, with the labels that each got.

#63 chore: 解决样式丢失问题
  .umirc.ts
Labels: ignore-for-release

#61 feat: 新增 RasterLayer
  docs/common/layer/raster-layer/source.md
  docs/common/layer/raster-layer/style.md
  package.json
  src/components/Layers/BaseLayers/RasterLayer/demos/default.tsx
  src/components/Layers/BaseLayers/RasterLayer/demos/rasterData.tsx
  src/components/Layers/BaseLayers/RasterLayer/demos/rasterImage.tsx
  src/components/Layers/BaseLayers/RasterLayer/index.md
  src/components/Layers/BaseLayers/RasterLayer/index.tsx
  src/components/Layers/BaseLayers/RasterLayer/types.ts
  src/components/Layers/index.ts
Labels: feature

#66 fix: 修复类型导出问题
  .github/workflows/release-notify.yml
  package.json
  src/components/LarkMap/demos/map-instance.tsx
  src/components/LarkMap/index.md
  src/components/Layers/index.ts
  src/index.ts
Labels: bugfix

#69 fix: 修复类型导出
  package.json
  src/index.ts
Labels: bugfix

#70 feat: 控件 ZoomControl 新增对 ReactNode 格式的支持
  package.json
  src/components/Control/ZoomControl/demos/default.tsx
  src/components/Control/ZoomControl/index.md
  src/components/Control/ZoomControl/index.tsx
  src/components/Control/hooks/index.ts
  src/components/Control/hooks/useControlElement.tsx
Labels: feature

#74 feat: 新增图例更新事件
  docs/common/layer/composite-common/event.md
  docs/common/layer/core-common/event.md
  package.json
  src/components/Layers/hooks/use-layer-event/constant.ts
  src/types/layer.ts
Labels: feature

#76 fix: 添加IconFontLayer、IconImageLayer 图层
  src/components/ContextMenu/index.less
  src/components/Layers/CompositeLayers/IconFontLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/IconFontLayer/index.md
  src/components/Layers/CompositeLayers/IconFontLayer/index.tsx
  src/components/Layers/CompositeLayers/IconFontLayer/types.ts
  src/components/Layers/CompositeLayers/IconImageLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/IconImageLayer/index.md
  src/components/Layers/CompositeLayers/IconImageLayer/index.tsx
  src/components/Layers/CompositeLayers/IconImageLayer/types.ts
  src/components/Layers/index.ts
Labels: bugfix

#77 chore: 迁移 formily 到 @antv/insight-component
  .fatherrc.ts
  .umirc.ts
  package.json
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.tsx
  src/components/LayerAttribute/components/ColorPicker/index.tsx
  src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx
  src/components/LayerAttribute/components/FieldSelect/index.tsx
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.less
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.tsx
  src/components/LayerAttribute/components/RibbonSelect/index.tsx
  src/components/LayerAttribute/components/index.ts
Labels: ignore-for-release

#78 fix: 颜色划分添加
  src/components/LayerAttribute/BubbleLayerStyle/helper.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerAttribute/common-schema/point-radius-collapse.ts
Labels: bugfix

#80 docs: 图层属性配置颜色划分默认值更改
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
Labels: documentation

#81 fix: label 标签配置优化
  src/components/LayerAttribute/BubbleLayerStyle/constant.ts
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/helper.ts
  src/components/LayerAttribute/BubbleLayerStyle/index.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/constant.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/helper.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx
  src/components/LayerAttribute/common-schema/lable-collapse.ts
  src/components/LayerAttribute/components/Offset/AntdOffset.less
  src/components/LayerAttribute/components/Offset/AntdOffset.tsx
  src/components/LayerAttribute/components/Offset/index.tsx
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx
  src/components/LayerAttribute/components/index.ts
  src/components/Layers/CompositeLayers/IconFontLayer/index.md
  src/components/Layers/CompositeLayers/IconImageLayer/index.md
Labels: bugfix
