Repository antvis/LarkMap, pull requests merged in 2022-08, with the labels that each got.

#29 chore: 调整布局问题
  src/components/LayerAttribute/components/Collapse/index.less
  src/components/LayerAttribute/components/Collapse/index.tsx
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.tsx
  src/components/LayerAttribute/components/ColorPicker/index.tsx
  src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.less
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx
Labels: ignore-for-release

#28 fix: 颜色选择组件
  package.json
  src/components/LayerAttribute/components/Collapse/index.less
  src/components/LayerAttribute/components/Collapse/index.tsx
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker.tsx
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.tsx
  src/components/LayerAttribute/components/ColorPicker/index.tsx
  src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.less
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.tsx
  src/components/LayerAttribute/components/RibbonSelect/ColorRibbon.less
  src/components/LayerAttribute/components/RibbonSelect/index.tsx
  src/components/LayerAttribute/components/Slider/AntdSlider.tsx
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.less
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx
Labels: bugfix

#31 docs: 新增 faq
  .umirc.ts
  docs/guide/faq.md
Labels: documentation

#27 feat: 新增气泡图层样式属性组件
  package.json
  src/components/LayerAttribute/BubbleLayerStyle/constant.ts
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/helper.ts
  src/components/LayerAttribute/BubbleLayerStyle/index.less
  src/components/LayerAttribute/BubbleLayerStyle/index.md
  src/components/LayerAttribute/BubbleLayerStyle/index.tsx
  src/components/LayerAttribute/BubbleLayerStyle/schema.ts
  src/components/LayerAttribute/BubbleLayerStyle/types.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/constant.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/helper.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/index.less
  src/components/LayerAttribute/ChoroplethLayerStyle/index.md
  src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/schema.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/types.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerAttribute/common-schema/lable-collapse.ts
  src/components/LayerAttribute/common-schema/point-radius-collapse.ts
  src/components/LayerAttribute/common-schema/stroke-collapse.ts
  src/components/LayerAttribute/components/Collapse/index.less
  src/components/LayerAttribute/components/Collapse/index.tsx
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.tsx
  src/components/LayerAttribute/components/ColorPicker/index.tsx
  src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx
  src/components/LayerAttribute/components/FieldSelect/index.tsx
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.less
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/index.tsx
  src/components/LayerAttribute/components/RibbonSelect/index.tsx
  src/components/LayerAttribute/components/Slider/AntdSlider.less
  src/components/LayerAttribute/components/Slider/AntdSlider.tsx
  src/components/LayerAttribute/components/Slider/index.tsx
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.less
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx
  src/components/LayerAttribute/components/SliderRange/index.tsx
  src/components/LayerAttribute/index.ts
  src/components/LayerAttribute/types/index.ts
  src/components/Layers/BaseLayers/PointLayer/demos/city-weather.json
  src/components/Layers/BaseLayers/PointLayer/demos/default.tsx
  src/components/Layers/BaseLayers/PolygonLayer/demos/default.tsx
  src/components/Layers/BaseLayers/PolygonLayer/demos/hangzhou-district.json
  src/components/Layers/BaseLayers/PolygonLayer/demos/xihu-district.json
  src/components/Layers/CompositeLayers/BubbleLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/ChoroplethLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/ChoroplethLayer/demos/xihu-district.json
  src/components/Template/index.md
  src/index.ts
  src/version.ts
Labels: feature

#34 chore: 给调试环境组件添加名称
  src/components/LarkMap/index.tsx
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/index.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/demos/default.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/index.tsx
  src/components/Layers/BaseLayers/LineLayer/demos/default.tsx
  src/components/Layers/BaseLayers/LineLayer/index.tsx
  src/components/Layers/BaseLayers/PointLayer/index.tsx
  src/components/Layers/BaseLayers/PolygonLayer/index.tsx
  src/components/Layers/BaseLayers/TextLayer/demos/default.tsx
  src/components/Layers/BaseLayers/TextLayer/index.tsx
  src/components/Layers/CompositeLayers/BubbleLayer/index.tsx
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.tsx
  src/components/Marker/index.tsx
  src/components/Popup/index.tsx
  src/components/ScaleControl/index.tsx
Labels: ignore-for-release

#36 chore: 地图容器组件加调试名称
  src/components/LarkMap/index.tsx
  src/components/LarkMap/types.ts
Labels: ignore-for-release

#33 feat: 热力图层样式属性组件
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/index.md
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/index.md
  src/components/LayerAttribute/HeatmapLayerStyle/constant.ts
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/helper.ts
  src/components/LayerAttribute/HeatmapLayerStyle/index.less
  src/components/LayerAttribute/HeatmapLayerStyle/index.md
  src/components/LayerAttribute/HeatmapLayerStyle/index.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/schema.ts
  src/components/LayerAttribute/HeatmapLayerStyle/types.ts
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
  src/components/LayerAttribute/components/Slider/AntdSlider.tsx
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.tsx
  src/components/LayerAttribute/index.ts
  src/components/Layers/BaseLayers/HeatmapLayer/demos/default.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/demos/mock.json
Labels: feature

#37 chore: 暴露图层管理器
  src/components/LarkMap/demos/default.tsx
  src/components/LarkMap/index.tsx
  src/components/LarkMap/types.ts
Labels: ignore-for-release

#39 fix: 问题修复
  src/components/LayerAttribute/HeatmapLayerStyle/helper.ts
Labels: bugfix

#40 docs: 更新图层文档示例
  .umirc.ts
  docs/common/layer/attribute/color.md
  docs/common/layer/attribute/scale.md
  docs/common/layer/attribute/size.md
  docs/common/layer/attribute/state.md
  docs/common/layer/composite-common/event.md
  docs/common/layer/core-common/event.md
  docs/common/layer/heatmap-layer/shape.md
  docs/common/layer/heatmap-layer/size.md
  docs/common/layer/heatmap-layer/style.md
  docs/common/layer/line-layer/animate.md
  docs/common/layer/line-layer/shape.md
  docs/common/layer/line-layer/source.md
  docs/common/layer/line-layer/style.md
  docs/common/layer/point-layer/animate.md
  docs/common/layer/point-layer/shape.md
  docs/common/layer/point-layer/source.md
  docs/common/layer/point-layer/style.md
  docs/common/layer/polygon-layer/shape.md
  docs/common/layer/polygon-layer/source.md
  docs/common/layer/polygon-layer/style.md
  docs/common/layer/text-layer/style.md
  docs/guide/faq.md
  package.json
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/components/FieldSelect/AntdSelect.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/demos/default.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/demos/mock.json
  src/components/Layers/BaseLayers/HeatmapLayer/index.md
  src/components/Layers/BaseLayers/LineLayer/demos/default.tsx
  src/components/Layers/BaseLayers/LineLayer/index.md
  src/components/Layers/BaseLayers/PointLayer/demos/city-weather.json
  src/components/Layers/BaseLayers/PointLayer/demos/default.tsx
  src/components/Layers/BaseLayers/PointLayer/index.md
  src/components/Layers/BaseLayers/PolygonLayer/demos/default.tsx
  src/components/Layers/BaseLayers/PolygonLayer/demos/hangzhou-district.json
  src/components/Layers/BaseLayers/PolygonLayer/index.md
  src/components/Layers/BaseLayers/TextLayer/demos/default.tsx
  src/components/Layers/BaseLayers/TextLayer/index.md
  src/components/Layers/CompositeLayers/BubbleLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/BubbleLayer/index.md
  src/components/Layers/CompositeLayers/ChoroplethLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.md
  src/components/Layers/hooks/use-create-layer.ts
  tsconfig.json
Labels: documentation

#42 docs: 更新面图层 API 文档
  src/components/Layers/BaseLayers/PolygonLayer/index.md
Labels: documentation

#43 fix: 修复属性组件样式问题
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
  src/components/LayerAttribute/components/Slider/AntdSlider.less
  src/components/LayerAttribute/components/SliderRange/AntdSliderRange.less
Labels: bugfix

#45 fix: 修复自定义颜色组件背景色
  src/components/LayerAttribute/components/ColorPicker/AntdColorPicker/index.less
Labels: bugfix

#50 chore: 规范方法名称
  src/components/LayerAttribute/LineLayerStyle/constant.ts
  src/components/LayerAttribute/LineLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/index.tsx
  src/components/LayerAttribute/index.ts
Labels: ignore-for-release
