Repository antvis/LarkMap, pull requests merged in 2022-11, with the labels that each got.

#82 fix: css名称修改
  src/components/LayerAttribute/components/Offset/AntdOffset.less
  src/components/LayerAttribute/components/Offset/AntdOffset.tsx
Labels: bugfix

#86 fix: 警告问题
  src/components/LayerAttribute/components/Offset/AntdOffset.tsx
Labels: bugfix

#90 docs: 更新 slogo
  README.md
  docs/guide/faq.md
  docs/guide/index.md
  docs/index.md
Labels: documentation

#92 feat: 线属性面板开启渐变效果
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/line-animate-collapse.ts
Labels: feature

#91 feat: 线图层动画属性配置面板
  src/components/LayerAttribute/BubbleLayerStyle/constant.ts
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/helper.ts
  src/components/LayerAttribute/BubbleLayerStyle/schema.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/constant.ts
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/line-animate-collapse.ts
  src/components/LayerAttribute/common-schema/point-animate-collapse.ts
Labels: feature

#94 docs: 更新图层文档路径
  docs/common/layer/base-common/event.md
  src/components/LarkMap/index.tsx
  src/components/LarkMap/types.ts
  src/components/Layers/BaseLayers/HeatmapLayer/index.md
  src/components/Layers/BaseLayers/ImageLayer/index.md
  src/components/Layers/BaseLayers/LineLayer/index.md
  src/components/Layers/BaseLayers/PointLayer/index.md
  src/components/Layers/BaseLayers/PolygonLayer/index.md
  src/components/Layers/BaseLayers/RasterLayer/index.md
  src/components/Layers/BaseLayers/TextLayer/index.md
  src/components/Layers/CompositeLayers/IconFontLayer/index.md
  src/components/Layers/CompositeLayers/IconImageLayer/index.md
Labels: documentation

#95 chore: 更新复合图层到最新依赖
  package.json
Labels: ignore-for-release

#96 docs: 图层事件文档补全
  docs/common/layer/base-common/event.md
  docs/common/layer/composite-common/event.md
  package.json
Labels: documentation

#102 docs: 更新链接地址
  docs/common/layer/image-layer/source.md
  docs/common/layer/line-layer/source.md
  docs/common/layer/point-layer/source.md
  docs/common/layer/polygon-layer/source.md
  docs/common/layer/raster-layer/source.md
  src/components/Control/CustomControl/index.md
  src/components/Control/ExportImageControl/index.md
  src/components/Control/FullscreenControl/index.md
  src/components/Control/GeoLocateControl/index.md
  src/components/Control/LayerSwitchControl/index.md
  src/components/Control/MapThemeControl/index.md
  src/components/Control/MouseLocationControl/index.md
  src/components/Control/ScaleControl/index.md
  src/components/Control/ZoomControl/index.md
  src/components/LarkMap/hooks/use-scene/use-scene.md
  src/components/LarkMap/index.md
  src/components/LarkMap/types.ts
  src/components/Layers/BaseLayers/HeatmapLayer/index.md
  src/components/Layers/BaseLayers/ImageLayer/index.md
  src/components/Layers/BaseLayers/LineLayer/index.md
  src/components/Layers/BaseLayers/PointLayer/index.md
  src/components/Layers/BaseLayers/PolygonLayer/index.md
  src/components/Layers/BaseLayers/RasterLayer/index.md
  src/components/Layers/BaseLayers/TextLayer/index.md
  src/components/Layers/CompositeLayers/BubbleLayer/index.md
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.md
  src/components/Layers/CompositeLayers/IconFontLayer/index.md
  src/components/Layers/CompositeLayers/IconImageLayer/index.md
Labels: documentation

#105 docs: 文档格式升级
  src/components/ContextMenu/index.md
  src/components/Control/CustomControl/index.md
  src/components/Control/ExportImageControl/index.md
  src/components/Control/FullscreenControl/index.md
  src/components/Control/GeoLocateControl/index.md
  src/components/Control/LayerSwitchControl/demos/default.tsx
  src/components/Control/LayerSwitchControl/index.md
  src/components/Control/MapThemeControl/index.md
  src/components/Control/MouseLocationControl/index.md
  src/components/Control/ScaleControl/index.md
  src/components/Control/ZoomControl/index.md
  src/components/Control/index.ts
  src/components/Draw/use-draw-group/index.md
  src/components/Draw/use-draw/demos/control.tsx
  src/components/Draw/use-draw/demos/default.tsx
  src/components/Draw/use-draw/demos/options.tsx
  src/components/Draw/use-draw/index.md
  src/components/LarkMap/hooks/use-layer/demos/constants.ts
  src/components/LarkMap/hooks/use-layer/demos/default.tsx
  src/components/LarkMap/hooks/use-layer/use-layer.md
  src/components/LarkMap/hooks/use-scene/demos/default.tsx
  src/components/LarkMap/hooks/use-scene/use-scene.md
  src/components/LarkMap/index.md
  src/components/LayerAttribute/BubbleLayerStyle/demos/default.tsx
  src/components/LayerAttribute/BubbleLayerStyle/index.md
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/index.md
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/index.md
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/index.md
  src/components/LayerPopup/index.md
  src/components/Layers/BaseLayers/HeatmapLayer/index.md
  src/components/Layers/BaseLayers/ImageLayer/index.md
  src/components/Layers/BaseLayers/LineLayer/index.md
  src/components/Layers/BaseLayers/PointLayer/index.md
  src/components/Layers/BaseLayers/PolygonLayer/index.md
  src/components/Layers/BaseLayers/RasterLayer/demos/rasterImage.tsx
  src/components/Layers/BaseLayers/RasterLayer/index.md
  src/components/Layers/BaseLayers/TextLayer/index.md
  src/components/Layers/CompositeLayers/BubbleLayer/index.md
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.md
  src/components/Layers/CompositeLayers/IconFontLayer/index.md
  src/components/Layers/CompositeLayers/IconImageLayer/demos/default.tsx
  src/components/Layers/CompositeLayers/IconImageLayer/index.md
  src/components/Legend/LegendCategories/demos/map-default.tsx
  src/components/Legend/LegendCategories/index.md
  src/components/Legend/LegendIcon/index.md
  src/components/Legend/LegendProportion/index.md
  src/components/Legend/LegendRamp/demos/map-default.tsx
  src/components/Legend/LegendRamp/index.md
  src/components/LocationSearch/index.md
  src/components/Marker/demos/custom.tsx
  src/components/Marker/demos/default.tsx
  src/components/Marker/index.md
  src/components/Popup/index.md
  src/components/Template/index.md
Labels: documentation

#107 docs: 文档内容修改
  .umirc.ts
  docs/index.md
Labels: bugfix

#108 docs: 新增 LarkMap 示例部分
  .umirc.ts
  docs/example/beijingHousePrice.md
  docs/example/beijingHousePrice/index.less
  docs/example/beijingHousePrice/index.tsx
  docs/example/beijingHousePrice/legend.tsx
  docs/example/californiaEarthquakes.md
  docs/example/californiaEarthquakes/index.tsx
  docs/example/californiaEarthquakesHeatmap.md
  docs/example/californiaEarthquakesHeatmap/index.tsx
  docs/example/countyUnemployment.md
  docs/example/countyUnemployment/index.tsx
  docs/example/countyUnemployment/utils.tsx
  docs/example/highSpeedRail.md
  docs/example/highSpeedRail/index.tsx
  docs/example/highspeedTime.md
  docs/example/highspeedTime/index.tsx
  docs/example/highspeedTime/mock.ts
  docs/example/iconFontLayer.md
  docs/example/iconFontLayer/index.tsx
  docs/example/iconImage.md
  docs/example/iconImage/index.tsx
  docs/example/losAngelesHomes.md
  docs/example/losAngelesHomes/index.tsx
  docs/example/marineConservation.md
  docs/example/marineConservation/Legend.tsx
  docs/example/marineConservation/constants.tsx
  docs/example/marineConservation/index.tsx
  docs/example/meteoriteLanding.md
  docs/example/meteoriteLanding/index.tsx
  docs/example/nycCensus.md
  docs/example/nycCensus/index.tsx
  docs/example/photoHotmap.md
  docs/example/photoHotmap/index.tsx
  docs/example/photoSpots.md
  docs/example/photoSpots/index.tsx
  docs/example/poiChart.md
  docs/example/poiChart/index.tsx
  docs/example/sanFranciscoStreetTreeMap.md
  docs/example/sanFranciscoStreetTreeMap/config.ts
  docs/example/sanFranciscoStreetTreeMap/index.less
  docs/example/sanFranciscoStreetTreeMap/index.tsx
  docs/example/sfContour.md
  docs/example/sfContour/index.tsx
  docs/example/shareBike/index.tsx
  docs/example/sharedBike.md
  docs/example/taxiTrips.md
  docs/example/taxiTrips/index.tsx
  docs/example/topicLayer.md
  docs/example/topicLayer/index.tsx
  docs/example/ukcommute.md
  docs/example/ukcommute/constants.tsx
  docs/example/ukcommute/index.tsx
  docs/example/worldHeritageListDataResources.md
  docs/example/worldHeritageListDataResources/index.tsx
  docs/guide/index.md
  package.json
  src/components/ContextMenu/index.md
  tsconfig.json
Labels: documentation

#109 docs: 更新 readme
  .umirc.ts
  README.en-US.md
  README.md
Labels: documentation

#110 fix: 属性配置面板颜色划分文案修改
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
Labels: feature

#113 docs: 更新 TextLayer padding 默认值
  docs/common/layer/text-layer/style.md
Labels: documentation
