Repository antvis/LarkMap, pull requests merged in 2022-12, with the labels that each got.

#112 fix: 属性配置 label 问题修复
  src/components/LayerAttribute/common-schema/label-collapse.ts
  src/components/LayerAttribute/components/Offset/AntdOffset.tsx
Labels: bugfix

#116 fix: 添补图层事件
  src/components/LarkMap/index.md
  src/components/Layers/hooks/use-create-layer/index.ts
  src/components/Layers/hooks/use-layer-event/constant.ts
  src/types/layer.ts
Labels: bugfix

#118 fix: 修改文档单词错误
  src/components/Control/ExportImageControl/index.md
Labels: bugfix

#119 chore: 忽略无效的图层事件
  src/components/LayerAttribute/LineLayerStyle/constant.ts
  src/components/Layers/hooks/use-layer-event/constant.ts
  src/types/layer.ts
Labels: ignore-for-release

#120 feat: 新增 useLayerList hook
  src/components/LarkMap/hooks/index.ts
  src/components/LarkMap/hooks/use-layer-list/demos/constants.ts
  src/components/LarkMap/hooks/use-layer-list/demos/default.tsx
  src/components/LarkMap/hooks/use-layer-list/index.ts
  src/components/LarkMap/hooks/use-layer-list/use-layer-manager.md
Labels: feature

#115 feat: 气泡图层 LayerPopup 对接 L7 LayerPopup 中的新增特性
  docs/example/highSpeedRail/index.tsx
  docs/example/marineConservation/index.tsx
  docs/example/poiChart.md
  package.json
  src/components/Control/ExportImageControl/index.tsx
  src/components/Control/FullscreenControl/index.tsx
  src/components/Control/GeoLocateControl/index.tsx
  src/components/Control/LayerSwitchControl/demos/default.tsx
  src/components/Control/LayerSwitchControl/index.tsx
  src/components/Control/MapThemeControl/index.tsx
  src/components/Control/MouseLocationControl/index.tsx
  src/components/Control/ScaleControl/index.tsx
  src/components/Control/ZoomControl/index.tsx
  src/components/LarkMap/hooks/use-layer-list/use-layer-list.md
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerPopup/demos/default.tsx
  src/components/LayerPopup/index.md
  src/components/LayerPopup/index.tsx
  src/components/LayerPopup/types.ts
  src/components/LayerPopup/utils.ts
  src/components/Popup/index.tsx
Labels: feature

#124 fix: 修复 LayerPopup 适配复合图层问题
  src/components/LayerPopup/index.md
  src/components/LayerPopup/index.tsx
  src/components/LayerPopup/types.ts
Labels: bugfix
