Repository antvis/LarkMap, pull requests merged in 2022-06, with the labels that each got.

#8 fix: 修复地图状态更新
  .umirc.ts
  package.json
  src/components/LarkMap/hooks/use-layer/demos/default.tsx
  src/components/LarkMap/index.tsx
  src/components/Layers/BubbleLayer/demos/default.tsx
  src/components/Layers/BubbleLayer/index.tsx
  src/components/Layers/ChoroplethLayer/demos/default.tsx
  src/components/Layers/ChoroplethLayer/index.tsx
  src/components/Layers/hooks/use-create-layer.ts
  src/version.ts
Labels: bugfix

#9 feat: 新增核心基础图层
  package.json
  src/components/LarkMap/hooks/use-control/index.ts
  src/components/Layers/BubbleLayer/index.md
  src/components/Layers/ChoroplethLayer/index.md
  src/components/Layers/HeatmapLayer/demos/default.tsx
  src/components/Layers/HeatmapLayer/index.md
  src/components/Layers/HeatmapLayer/index.tsx
  src/components/Layers/HeatmapLayer/types.ts
  src/components/Layers/LineLayer/demos/default.tsx
  src/components/Layers/LineLayer/index.md
  src/components/Layers/LineLayer/index.tsx
  src/components/Layers/LineLayer/types.ts
  src/components/Layers/PointLayer/demos/default.tsx
  src/components/Layers/PointLayer/index.md
  src/components/Layers/PointLayer/index.tsx
  src/components/Layers/PointLayer/types.ts
  src/components/Layers/PolygonLayer/demos/default.tsx
  src/components/Layers/PolygonLayer/demos/xihu-district.json
  src/components/Layers/PolygonLayer/index.md
  src/components/Layers/PolygonLayer/index.tsx
  src/components/Layers/PolygonLayer/types.ts
  src/components/Layers/TextLayer/demos/default.tsx
  src/components/Layers/TextLayer/index.md
  src/components/Layers/TextLayer/index.tsx
  src/components/Layers/TextLayer/types.ts
  src/components/Layers/hooks/use-create-layer.ts
  src/components/Layers/index.ts
Labels: feature

#11 chore: 规范包引入顺序
  src/components/CustomControl/index.tsx
  src/components/LarkMap/index.tsx
  src/components/Layers/BubbleLayer/index.tsx
  src/components/Layers/ChoroplethLayer/index.tsx
  src/components/Layers/HeatmapLayer/index.tsx
  src/components/Layers/LineLayer/index.tsx
  src/components/Layers/PointLayer/index.tsx
  src/components/Layers/PolygonLayer/index.tsx
  src/components/Layers/TextLayer/index.tsx
  src/components/Scale/index.tsx
  src/components/Template/index.tsx
  src/components/Zoom/index.tsx
  src/index.ts
Labels: ignore-for-release

#12 feat: 新增 marker 组件
  src/components/CustomControl/types.ts
  src/components/Marker/demos/default.tsx
  src/components/Marker/index.md
  src/components/Marker/index.tsx
  src/components/Marker/types.ts
  src/components/Scale/index.tsx
  src/components/Scale/types.ts
  src/components/Zoom/index.tsx
  src/components/Zoom/types.ts
  src/index.ts
Labels: feature

#14 chore: v0.0.1-alpha.5
  package.json
  src/version.ts
Labels: ignore-for-release

#15 fix: 修复资源注册问题
  src/components/CustomControl/index.md
  src/components/LarkMap/index.tsx
  src/components/Marker/index.md
  src/components/Marker/index.tsx
  src/components/Marker/types.ts
  src/components/Popup/demos/default.tsx
  src/components/Popup/index.md
  src/components/Popup/types.ts
  src/components/Scale/index.md
  src/components/Template/index.md
  src/components/Zoom/index.md
Labels: bugfix

#16 chore: v0.0.1-alpha.6
  package.json
  src/version.ts
Labels: ignore-for-release

#19 fix: 修复类型问题
  src/components/Layers/BubbleLayer/index.md
  src/components/Scale/types.ts
  src/components/Zoom/types.ts
Labels: bugfix

#20 feat: 新增 useDraw 用于对接 L7Draw
  package.json
  src/components/Draw/types.ts
  src/components/Draw/use-draw/constant.ts
  src/components/Draw/use-draw/demos/default.tsx
  src/components/Draw/use-draw/index.md
  src/components/Draw/use-draw/index.ts
  src/components/Draw/use-draw/types.ts
  src/index.ts
Labels: feature
