Repository antvis/LarkMap, pull requests merged in 2022-09, with the labels that each got.

#52 fix: 属性组件更改输入input为滑块组件/色带颜色更改
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/common-schema/lable-collapse.ts
  src/components/LayerAttribute/common-schema/stroke-collapse.ts
  src/components/LayerAttribute/components/RibbonSelect/AntdRibbonSelect/constants.ts
Labels: bugfix

#53 chore: 规范方法名称
  src/components/LayerAttribute/index.ts
Labels: ignore-for-release

#54 feat: 新增 Scene 与 Layer 相关的事件属性
  docs/common/layer/composite-common/event.md
  docs/common/layer/core-common/event.md
  docs/guide/index.md
  package.json
  src/components/LarkMap/hooks/use-layer/index.ts
  src/components/LarkMap/hooks/use-scene-event/constant.ts
  src/components/LarkMap/hooks/use-scene-event/index.ts
  src/components/LarkMap/index.md
  src/components/LarkMap/index.tsx
  src/components/LarkMap/types.ts
  src/components/Layers/BaseLayers/HeatmapLayer/index.tsx
  src/components/Layers/BaseLayers/HeatmapLayer/types.ts
  src/components/Layers/BaseLayers/LineLayer/index.tsx
  src/components/Layers/BaseLayers/LineLayer/types.ts
  src/components/Layers/BaseLayers/PointLayer/index.tsx
  src/components/Layers/BaseLayers/PointLayer/types.ts
  src/components/Layers/BaseLayers/PolygonLayer/index.tsx
  src/components/Layers/BaseLayers/PolygonLayer/types.ts
  src/components/Layers/BaseLayers/TextLayer/index.tsx
  src/components/Layers/BaseLayers/TextLayer/types.ts
  src/components/Layers/CompositeLayers/BubbleLayer/index.tsx
  src/components/Layers/CompositeLayers/BubbleLayer/types.ts
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.tsx
  src/components/Layers/CompositeLayers/ChoroplethLayer/types.ts
  src/components/Layers/hooks/index.ts
  src/components/Layers/hooks/use-create-layer/index.ts
  src/components/Layers/hooks/use-layer-event/constant.ts
  src/components/Layers/hooks/use-layer-event/index.ts
  src/types/common.ts
  src/types/index.ts
  src/types/layer.ts
  src/utils/layer-manager.ts
Labels: feature

#56 feat: 右键菜单组件
  src/components/ContextMenu/ContextMenuItem.tsx
  src/components/ContextMenu/constant.ts
  src/components/ContextMenu/demos/custom.tsx
  src/components/ContextMenu/demos/default.tsx
  src/components/ContextMenu/index.less
  src/components/ContextMenu/index.md
  src/components/ContextMenu/index.tsx
  src/components/ContextMenu/types.ts
  src/index.ts
Labels: feature

#59 fix: 右键菜单项类型问题
  src/components/ContextMenu/index.md
  src/components/ContextMenu/index.tsx
Labels: bugfix

#60 fix: 修复地点搜索返回结果未过滤不含坐标值的问题
  src/components/LocationSearch/index.tsx
Labels: bugfix

#55 feat: 添加图例组件
  src/components/LegendCategories/demos/default.tsx
  src/components/LegendCategories/demos/map-default.tsx
  src/components/LegendCategories/index.less
  src/components/LegendCategories/index.md
  src/components/LegendCategories/index.tsx
  src/components/LegendCategories/types.ts
  src/components/LegendIcon/demos/default.tsx
  src/components/LegendIcon/demos/map-default.tsx
  src/components/LegendIcon/index.less
  src/components/LegendIcon/index.md
  src/components/LegendIcon/index.tsx
  src/components/LegendIcon/types.ts
  src/components/LegendProportion/demos/default.tsx
  src/components/LegendProportion/demos/index.less
  src/components/LegendProportion/demos/map-default.tsx
  src/components/LegendProportion/index.less
  src/components/LegendProportion/index.md
  src/components/LegendProportion/index.tsx
  src/components/LegendProportion/types.ts
  src/components/LegendRamp/demos/default.tsx
  src/components/LegendRamp/demos/map-default.tsx
  src/components/LegendRamp/index.less
  src/components/LegendRamp/index.md
  src/components/LegendRamp/index.tsx
  src/components/LegendRamp/types.ts
  src/index.ts
  src/utils/color.ts
Labels: feature
