Repository antvis/LarkMap, pull requests merged in 2023-02, with the labels that each got.

#126 fix: 修改图例映射区间问题
  src/components/Layers/hooks/use-create-layer/index.ts
  src/components/Legend/LegendProportion/demos/map-default.tsx
  src/components/Legend/LegendRamp/demos/default.tsx
  src/components/Legend/LegendRamp/demos/map-default.tsx
  src/components/Legend/LegendRamp/index.less
  src/components/Legend/LegendRamp/index.tsx
  src/components/Legend/LegendRamp/types.ts
Labels: bugfix

#133 feat: 新增地图状态同步方法 syncScene
  docs/example/syncScene.md
  src/index.ts
  src/utils/syncScene.ts
Labels: feature

#135 feat: 新增 Logo 控件
  src/components/Control/LogoControl/demos/default.tsx
  src/components/Control/LogoControl/index.md
  src/components/Control/LogoControl/index.tsx
  src/components/Control/LogoControl/types.ts
  src/components/Control/index.ts
Labels: feature

#137 chore: add chatgpt ci
  .github/workflows/chatgpt.yml
Labels: ignore-for-release

#141 feat:迁移属性面板到区块
  docs/blocks/layer-attribute/bubble-layer-style-attribute.md
  docs/blocks/layer-attribute/bubble-layer-style-attribute/demos/default.tsx
  docs/blocks/layer-attribute/bubble-layer-style-attribute/index.md
  docs/blocks/layer-attribute/choropleth-layer-style-attribute/demos/default.tsx
  docs/blocks/layer-attribute/choropleth-layer-style-attribute/index.md
  docs/blocks/layer-attribute/heatmap-layer-style-attribute/demos/default.tsx
  docs/blocks/layer-attribute/heatmap-layer-style-attribute/index.md
  docs/blocks/layer-attribute/line-layer-style-attribute/demos/default.tsx
  docs/blocks/layer-attribute/line-layer-style-attribute/index.md
  package.json
Labels: feature

#142 feat: 去除 LocationSearch 对 Ant Design 的依赖
  package.json
  src/components/LocationSearch/Select/index.less
  src/components/LocationSearch/Select/index.tsx
  src/components/LocationSearch/index.md
  src/components/LocationSearch/index.tsx
Labels: feature

#136 feat: 下载行政区域页面demo
  docs/example/regionDownload.md
  docs/example/regionDownload/data/dataSource.ts
  docs/example/regionDownload/index.less
  docs/example/regionDownload/index.tsx
  docs/example/regionDownload/util.ts
  package.json
Labels: feature

#143 feat: 区域数据下载优化
  docs/examples/regionDownload.md
  docs/examples/regionDownload/data/dataSource.ts
  docs/examples/regionDownload/index.less
  docs/examples/regionDownload/index.tsx
  docs/examples/regionDownload/util.ts
Labels: feature

#144 chore: datasource
  docs/region/data/BaseDataSource.ts
  docs/region/data/dataSource.ts
  docs/region/data/datavSource.ts
  docs/region/data/index.ts
  docs/region/data/l7Source.ts
  docs/region/index.less
  docs/region/index.tsx
  docs/region/regionDownload.md
  docs/region/util.ts
  tsconfig.json
Labels: ignore-for-release

#146 docs: 移除旧文档
  docs/examples/regionDownload.md
  docs/region/regionDownload.md
Labels: documentation

#147 chore: v1.3.0
  package.json
  src/version.ts
Labels: ignore-for-release

#150 fix: 修复 Scene 事件绑定问题
  src/components/LarkMap/hooks/use-scene-event/constant.ts
  src/components/LarkMap/hooks/use-scene-event/index.ts
Labels: bugfix

#151 fix: 修复 ContextMenu 去 antd 样式依赖问题
  src/components/ContextMenu/index.less
  src/components/LocationSearch/types.ts
Labels: bugfix

#149 chore: 行政区划显示页面代码优化
  docs/region/data/BaseDataSource.ts
  docs/region/data/dataSource.ts
  docs/region/data/datavSource.ts
  docs/region/data/index.ts
  docs/region/data/l7Source.ts
  docs/region/index.less
  docs/region/index.tsx
  docs/region/util.ts
Labels: ignore-for-release

#153 chore: 更新数据源 URL
  docs/region/data/l7Source.ts
Labels: ignore-for-release
