Repository antvis/LarkMap, pull requests merged in 2023-11, with the labels that each got.

#193 fix: 修复地图token失效问题
  .umirc.ts
  package.json
Labels: bugfix

#194 feat: 地图类型新增对百度和腾讯地图的支持
  src/components/LarkMap/helper.ts
  src/components/LarkMap/index.md
  src/components/LarkMap/types.ts
Labels: feature

#195 docs: 补充 layerSwitch 文档和 demo
  src/components/Control/LayerSwitchControl/demos/layerSwitchItem.tsx
  src/components/Control/LayerSwitchControl/index.md
Labels: documentation

#198 fix: offset 修复为 offsets
  src/components/Marker/types.ts
Labels: bugfix

#200 fix: 修复 ContextMenu.Item 类型错误
  src/components/ContextMenu/index.tsx
Labels: bugfix
