Repository antvis/LarkMap, pull requests merged in 2023-01, with the labels that each got.

#122 feat: 属性面板颜色划分类型根据字段展示不同选项
  src/components/LayerAttribute/BubbleLayerStyle/index.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/index.tsx
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/index.tsx
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerAttribute/components/ScaleSelector/AntdScaleSelector.tsx
  src/components/LayerAttribute/components/ScaleSelector/constants.ts
  src/components/LayerAttribute/components/ScaleSelector/index.tsx
  src/components/LayerAttribute/components/index.ts
Labels: feature

#127 docs: label 支持 position
  .umirc.ts
  package.json
  src/components/Layers/CompositeLayers/ChoroplethLayer/index.md
Labels: documentation

#129 feat: 新版属性颜色色带组件
  src/components/LayerAttribute/BubbleLayerStyle/helper.ts
  src/components/LayerAttribute/BubbleLayerStyle/index.tsx
  src/components/LayerAttribute/BubbleLayerStyle/schema.ts
  src/components/LayerAttribute/BubbleLayerStyle/types.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/demos/default.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/helper.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/index.tsx
  src/components/LayerAttribute/ChoroplethLayerStyle/schema.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/types.ts
  src/components/LayerAttribute/HeatmapLayerStyle/constant.ts
  src/components/LayerAttribute/HeatmapLayerStyle/demos/default.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/helper.ts
  src/components/LayerAttribute/HeatmapLayerStyle/index.tsx
  src/components/LayerAttribute/HeatmapLayerStyle/schema.ts
  src/components/LayerAttribute/HeatmapLayerStyle/types.ts
  src/components/LayerAttribute/LineLayerStyle/demos/default.tsx
  src/components/LayerAttribute/LineLayerStyle/helper.ts
  src/components/LayerAttribute/LineLayerStyle/index.tsx
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/LineLayerStyle/types.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerAttribute/common-schema/label-collapse.ts
  src/components/LayerAttribute/common-schema/other-attributes-collapse.ts
  src/components/LayerAttribute/common-schema/point-radius-collapse.ts
  src/components/LayerAttribute/components/index.ts
  src/components/LayerAttribute/types/index.ts
Labels: feature

#130 docs: 补充全屏组件 FullscreenControl 与 Antd 同时使用的说明
  src/components/Control/FullscreenControl/demos/antd.tsx
  src/components/Control/FullscreenControl/index.md
Labels: documentation

#131 chore: 导出 OptionsType 名称修改
  src/components/LayerAttribute/BubbleLayerStyle/schema.ts
  src/components/LayerAttribute/ChoroplethLayerStyle/schema.ts
  src/components/LayerAttribute/HeatmapLayerStyle/schema.ts
  src/components/LayerAttribute/LineLayerStyle/schema.ts
  src/components/LayerAttribute/common-schema/fill-color-collapse.ts
  src/components/LayerAttribute/common-schema/label-collapse.ts
  src/components/LayerAttribute/common-schema/other-attributes-collapse.ts
  src/components/LayerAttribute/common-schema/point-radius-collapse.ts
  src/components/LayerAttribute/types/index.ts
Labels: bugfix

#132 fix: 修复地图倾角更新不生效问题
  src/components/LarkMap/index.tsx
Labels: bugfix
